bookstore_cms/config/routes.rb
Rails.application.routes.draw do
  root "books#index"
  resources :users, :except => [:index]
  resources :sessions, only: [:new, :create]
  resources :books
  resources :authors


  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"


  get '/auth/:provider/callback' => 'sessions#create'
    
  

end

bookstore_cms/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_cms/app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

bookstore_cms/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    belongs_to :administrator,
        class_name: "User",
        foreign_key: "user_id"
    has_many :categories, through: :category_books, source: :category
    has_many :book_genres, through: :genre_books, source: :genre
    has_many :reviews, dependent: :destroy
end

bookstore_cms/app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :books, through
end

bookstore_cms/app/models/cart_book.rb
class CartBook < ApplicationRecord
    belongs_to :book 
    belongs_to :cart
end

bookstore_cms/app/models/category.rb
class Category < ApplicationRecord
    has_many :books, through: :category_books, source: :book
end

bookstore_cms/app/models/category_book.rb
class CategoryBook < ApplicationRecord
    belongs_to :category
    belongs_to :book
end

bookstore_cms/app/models/genre.rb
class Genre < ApplicationRecord
    has_many :genre_books through: :genre_book, source: :book
end

bookstore_cms/app/models/genre_book.rb
class GenreBook < ApplicationRecord
    belongs_to :book 
    belongs_to :genre
end

bookstore_cms/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :reviewer,
        :class_name => "User"
        :foreign_kay => "user_id"
end

bookstore_cms/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness:true
    validates :name, presence: true
    
    has_many :books
    has_many :reviews

    def self.find_or_create_by_omniauth(auth_hash)
        # Creates a new user only if it doesn't exist
        self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end
end

bookstore_cms/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.all
        #change to sorted after adding lamdas scope thing
      end
    
      def show
        @author = Author.find(params[:id])
      end
    
      def new
        @author = Author.new
      end
    
      def create
        @author = Author.new(author_params)
        if @author.save
          flash[:notice] = "author created successfully."
          redirect_to(authors_path)
        else
          render('new')
        end
      end
    
      def edit
        @author = Author.find(params[:id])
      end
    
      def update
        @author = Author.find(params[:id])
        if @author.update_attributes(author_params)
          flash[:notice] = "author updated successfully."
          redirect_to(author_path(@author))
        else
          render('edit')
        end
      end
    
      def delete
        @author = author.find(params[:id])
      end
    
      def destroy
        @author = author.find(params[:id])
        @author.destroy
        flash[:notice] = "author destroyed successfully."
        redirect_to(authors_path)
      end
    
      private
    
      def author_params
        params.require(:author).permit(
          :name)
      end
end

bookstore_cms/app/controllers/books_controller.rb
class BooksController < ApplicationController
  #add admin to all of this
  def index
    @books = Book.all
    #change to sorted after adding lamdas scope thing
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "book created successfully."
      redirect_to(books_path)
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "book updated successfully."
      redirect_to(book_path(@book))
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "book destroyed successfully."
    redirect_to(books_path)
  end

  private

  def book_params
    params.require(:book).permit(
      :title, 
      :isbn,
      :description, 
      :author_id, 
      :quantity, 
      :condition,
      :price,
      :year_published)
  end
end

bookstore_cms/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.all
    #change to sorted after adding lamdas scope thing
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      flash[:notice] = "cart created successfully."
      redirect_to(carts_path)
    else
      render('new')
    end
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def update
    @cart = Cart.find(params[:id])
    if @cart.update_attributes(cart_params)
      flash[:notice] = "cart updated successfully."
      redirect_to(cart_path(@cart))
    else
      render('edit')
    end
  end

  def delete
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    flash[:notice] = "cart destroyed successfully."
    redirect_to(carts_path)
  end

  private

  def cart_params
    params.require(:cart).permit(
      :user_id)
  end
end

bookstore_cms/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_path
    end
  end

  def show
    @user = User.find_by(:id => params[:id])
    if logged_in? && current_user == @user
      render :show
    else
      redirect_to new_session_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.authenticate(params[:user][:old_password])
      if @user.update(user_params)
        redirect_to user_path(@user)
      else
        render :edit
      end
    else
      render :edit
    end
  end
  
  private

      def user_params
        params.require(:user).permit(:name, :email, :password)
      end

end

bookstore_cms/app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

    def logged_in?
        !!session[:user_id]
    end
end

bookstore_cms/app/helpers/author_helper.rb
module AuthorHelper
end

bookstore_cms/app/helpers/book_helper.rb
module BookHelper
end

bookstore_cms/app/helpers/cart_helper.rb
module CartHelper
end

bookstore_cms/app/helpers/categories_helper.rb
module CategoriesHelper
end

bookstore_cms/app/helpers/reviews_helper.rb
module ReviewsHelper
end

bookstore_cms/app/helpers/session_helper.rb
module SessionHelper
end

bookstore_cms/app/helpers/user_helper.rb
module UserHelper
end

bookstore_cms/app/views/authors/index.html.erb
<% @author_title = "All authors" %>
<div class= "authors index">
    <h2> Authors </h2>

<%= link_to("Add New author", new_author_path, :class => 'action new') %>
<%= link_to("Create Author", new_author_path, :class => 'action new') %>

<table class="listing" summary="author list">
  <tr class="header">
    <th>Name</th>
  </tr>
  <% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    
    <td class="actions">
      <%= link_to("Show", author_path(author), :class => 'action show') %>
      <%= link_to("Edit", edit_author_path(author), :class => 'action edit') %>
      
    </td>
  </tr>
  <% end %>
</table>
</div>

bookstore_cms/app/views/authors/new.html.erb
<h1>Author#new</h1>
<p>Find me in app/views/author/new.html.erb</p>
<%= link_to("<< Back to List", authors_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create author</h2>

  <%= form_for(@author) do |f| %>

    <table summary="author form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      
</table>
    <div class="form-buttons">
      <%= f.submit("Create Author") %>
    </div>

  <% end %>
</div>

bookstore_cms/app/views/books/_form.html.erb
<table summary="Page form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
  <tr>
    <th>ISBN</th>
    <td><%= f.text_field(:isbn) %></td>
  </tr>
  <tr>
    <th>Author</th>
    <td><%= f.text_field(:author) %></td>
  </tr>
  <tr>
    <th>Quantity</th>
    <td><%= f.text_field(:quantity) %></td>
  </tr>
  <tr>
    <th>Condition</th>
    <td><%= f.text_field(:condition) %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.text_field(:price) %></td>
  </tr>
  <tr>
    <th>Year_Published</th>
    <td><%= f.text_field(:published) %></td>
  </tr>
</table>

bookstore_cms/app/views/books/delete.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this book?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

bookstore_cms/app/views/books/edit.html.erb
<% @book_title = "Edit book" %>

<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Update book</h2>

  <%= form_for(@book) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update book") %>
    </div>

  <% end %>
</div>

bookstore_cms/app/views/books/index.html.erb
<% @book_title = "All books" %>
<div class= "books index">
    <h2> Boooks </h2>

<%= link_to("Add New Book", new_book_path, :class => 'action new') %>
<%= link_to("Create Author", new_author_path, :class => 'action new') %>

<table class="listing" summary="Book list">
  <tr class="header">
    <th>Title</th>
    <th>ISBN</th>
    <th>Description</th>
    <th>Author</th>
    <th>Quantity</th>
    <th>Condition</th>
    <th>Price</th>
    <th>Year_published</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.isbn %></td>
    <td><%= book.description%></td>
    <td><%= book.author_id %></td>
    <td><%= book.quantity %></td>
    td><%= book.condition %></td>
    td><%= book.price %></td>
    td><%= book.year_published%></td>
    <td class="center"><%= status_tag(book.visible) %></td>
    <td class="center"><%= book.sections.size %></td>
    <td class="actions">
      <%= link_to("Show", book_path(book), :class => 'action show') %>
      <%= link_to("Edit", edit_book_path(book), :class => 'action edit') %>
      <%= link_to("Delete", delete_book_path(book), :class => 'action delete') %>
    </td>
  </tr>
  <% end %>
</table>
</div>

bookstore_cms/app/views/books/new.html.erb
<h1>Book#new</h1>
<p>Find me in app/views/book/new.html.erb</p>
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>ISBN</th>
        <td><%= f.text_field(:isbn) %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= f.text_field(:description) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Quantity</th>
        <td><%= f.text_field(:quantity) %></td>
      </tr>
      <tr>
        <th>Condition</th>
        <td><%= f.text_field(:condition) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Year Published</th>
        <td><%= f.text_field(:year_published) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create book") %>
    </div>

  <% end %>
</div>

bookstore_cms/app/views/books/show.html.erb
<h1>Book#show</h1>
<p>Find me in app/views/book/show.html.erb</p>

bookstore_cms/app/views/carts/index.html.erb
<h1>Cart#index</h1>
<p>Find me in app/views/cart/index.html.erb</p>

bookstore_cms/app/views/carts/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

bookstore_cms/app/views/users/index.html.erb
<h1 style="color: white; margin: 35px 10px;">Sign Up!</h1>


  <div class="container" >
    <div class="row">
      <div class="col-sm-8">
        <div class="jumbotron" style="background: white; border-radius:10px; margin-top: 10px;">
          

          <h1>Sign Up!</h1>
          <form action="/signup" method="POST">
            <% if flash.has?(:message) %>
            <p style="color:#f0ad4e;"><%= flash[:message] %> </p>
            <% end %>
            <p><label for="username">Username:</label>
            <input type="text" autocomplete="off" name="username" placeholder="username..."></p>
            <p><label for="email">Email:</label>
            <input type="email" autocomplete="off" name="email" placeholder="email..."></p>
            <p><label for="password">Password:</label>
            <input type="password" autocomplete="off" name="password" placeholder="password..."></p>
            <button type="submit" class="btn btn-info">Submit</button>
          </form>

      </div><!--end jumbotron -->
    </div><!--end col-sm-8 -->
  </div><!-- end row -->
</div><!-- end container -->


<% unless current_user %>
    <%= link_to "Sign in with Github", user_github_omniauth_authorize_path %>
<% else %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>

bookstore_cms/app/views/users/new.html.erb
<h1 style="color: white; margin: 35px 10px;">Sign Up!</h1>


  <div class="container" >
    <div class="row">
      <div class="col-sm-8">
        <div class="jumbotron" style="background: white; border-radius:10px; margin-top: 10px;">
          

          <h1>Sign Up!</h1>
          <form action="/signup" method="POST">
            <% if flash.has?(:message) %>
            <p style="color:#f0ad4e;"><%= flash[:message] %> </p>
            <% end %>
            <p><label for="username">Username:</label>
            <input type="text" autocomplete="off" name="username" placeholder="username..."></p>
            <p><label for="email">Email:</label>
            <input type="email" autocomplete="off" name="email" placeholder="email..."></p>
            <p><label for="password">Password:</label>
            <input type="password" autocomplete="off" name="password" placeholder="password..."></p>
            <button type="submit" class="btn btn-info">Submit</button>
          </form>

      </div><!--end jumbotron -->
    </div><!--end col-sm-8 -->
  </div><!-- end row -->
</div><!-- end container -->

bookstore_cms/app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>